FROM node:18-alpine

WORKDIR /app

COPY relayer/package*.json ./relayer/
RUN cd relayer && npm install

COPY relayer ./relayer
COPY .env ./

WORKDIR /app/relayer

EXPOSE 4000

CMD ["node", "server.js"]